tr_data_fname: train_v4_rnn_nonorm_febtofeb_y1-7_stackedhalfyear_gzip8_chunk1_subset.h5
val_data_fname: data_v4_rnn_nonorm_year8_nocompress_chunk3.h5
tr_data_dir: "/data/phys-climsim/low-res-expanded/train/preprocessed/"
val_data_dir: "/data/phys-climsim/low-res-expanded/train/preprocessed/"

cache: true
num_workers: 4
chunksize_train: 42
chunksize_val: 14
val_epoch_start: 0

autoregressive: true
mp_mode: 1

input_norm_per_level: false
output_norm_per_level: false
new_nolev_scaling: true
#loss_fn_type: mse
#loss_fn_type: huber
loss_fn_type: CRPS
use_energy_loss: true
#_lambda: 5.0e-06
#_lambda: 1.0e-05
use_water_loss: true 
#_alpha: 5.0e4
add_stochastic_layer: true # = train on CRPS, ensemble NN
beta: 2.0 # 1.0 is CRPS, but may need higher emphasis on MAE for stability
_lambda: 5.0e-05 # weight for moist static energy loss 
_alpha: 1.5e5 # weight for water con loss
nh_mem: 16

#input_norm_per_level: false
#output_norm_per_level: false
#loss_fn_type: huber
#_lambda: 5.0e-06
#use_energy_loss: false
output_prune: true
qinput_prune: true
rh_prune: true
remove_past_sfc_inputs: true
v4_to_v5_inputs: false
snowhice_fix: true

nneur:
- 160
- 160
#- 128

add_pres: true
add_refpres: false
use_initial_mlp: true
use_intermediate_mlp: true
concat: false
memory: Hidden
model_type: SRNN
separate_radiation: false

save_model: true
use_wandb: true
num_epochs: 20
lr: 0.001
mp_autocast: true
use_scaler: true
shuffle_data: false
timestep_scheduling: true
optimizer: adam
#optimizer: adamwschedulefree
rollout_schedule:
- 1
- 1
- 2
- 2
- 2
- 2
- 2
- 2
- 2
- 2
