tr_data_fname: train_v4_rnn_nonorm_febtofeb_y1-7_stackedhalfyear_gzip8_chunk1_subset.h5
val_data_fname: data_v4_rnn_nonorm_year8_nocompress_chunk3.h5
tr_data_dir: "/data/phys-climsim/low-res-expanded/train/preprocessed/"
val_data_dir: "/data/phys-climsim/low-res-expanded/train/preprocessed/"
#tr_data_dir: "/media/peter/CrucialP1/data/ClimSim/low_res_expanded/"
#val_data_dir: "/media/peter/CrucialP1/data/ClimSim/low_res_expanded/"
#tr_data_dir: "/local/scratch/ukkonenp/"
#val_data_dir: "/local/scratch/ukkonenp/"

# cache option: during the first epoch, as the data is loaded it is put in shared (RAM) memory, 
# from which it is loaded in subsequent epochs
# this allows to use multiple workers and fast RAM memory without copying the data to each worker, 
# which is especially useful on systems without SSDs. If the data is on a fast SSD, there is no need
# to put the data in memory assuming multiple workers and prefetching is used
cache: true
val_cache: false 
num_workers: 4
chunksize_train: 24
chunksize_val: 14
val_epoch_start: 0

autoregressive: true
use_ar_noise: false
mp_mode: 1
input_norm_per_level: true
output_norm_per_level: true
new_nolev_scaling: false
loss_fn_type: CRPS
use_energy_loss: false
w_hcon: 1.0e-05
use_water_loss: false
w_wcon: 3.0e7
use_bias_loss: false
w_bias: 1.0e5
output_prune: true
qinput_prune: true
rh_prune: true
remove_past_sfc_inputs: true
v4_to_v5_inputs: false
include_prev_inputs: false
include_prev_outputs: false
use_surface_memory: false
snowhice_fix: true

add_pres: true
add_refpres: false
use_initial_mlp: true
use_intermediate_mlp: true
memory: Hidden
model_type: LSTM
concat: false
separate_radiation: false

add_stochastic_layer: true
beta: 1.0
model_path_det: "saved_models/LSTM-Hidden_lr0.001.neur160-160_xv4_yv5_num33706.pt"
nh_mem: 16
nneur:
- 160
- 160
ensemble_size: 2

save_model: true
use_wandb: true
num_epochs: 30
lr: 0.001
timestepped_optimizer: false
mp_autocast: true
use_scaler: true
shuffle_data: false
timestep_scheduling: true
optimizer: soap
#optimizer: adamwschedulefree
rollout_schedule:
- 1
- 2
- 2
- 2
- 3
- 3
- 4
- 4
- 4
- 4
swap_true_mem_with_pred_epoch: 0
